# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/Program/Python/Tool/Host/ui\camera.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CameraWidget(object):
    def setupUi(self, CameraWidget):
        CameraWidget.setObjectName("CameraWidget")
        CameraWidget.resize(785, 549)
        CameraWidget.setMinimumSize(QtCore.QSize(640, 480))
        CameraWidget.setStyleSheet("font: 9pt \"Microsoft JhengHei UI\";")
        self.verticalLayout = QtWidgets.QVBoxLayout(CameraWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(CameraWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.posxDoubleSpinBox = QtWidgets.QDoubleSpinBox(CameraWidget)
        self.posxDoubleSpinBox.setObjectName("posxDoubleSpinBox")
        self.horizontalLayout_2.addWidget(self.posxDoubleSpinBox)
        self.label_3 = QtWidgets.QLabel(CameraWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.posyDoubleSpinBox = QtWidgets.QDoubleSpinBox(CameraWidget)
        self.posyDoubleSpinBox.setObjectName("posyDoubleSpinBox")
        self.horizontalLayout_2.addWidget(self.posyDoubleSpinBox)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.startButton = QtWidgets.QPushButton(CameraWidget)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        spacerItem1 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(CameraWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.xEdit = QtWidgets.QLineEdit(CameraWidget)
        self.xEdit.setObjectName("xEdit")
        self.horizontalLayout_3.addWidget(self.xEdit)
        self.label_4 = QtWidgets.QLabel(CameraWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.yEdit = QtWidgets.QLineEdit(CameraWidget)
        self.yEdit.setObjectName("yEdit")
        self.horizontalLayout_3.addWidget(self.yEdit)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(3, 5)
        self.horizontalLayout.setStretch(4, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.imgLabel = QtWidgets.QLabel(CameraWidget)
        self.imgLabel.setMinimumSize(QtCore.QSize(640, 480))
        self.imgLabel.setMaximumSize(QtCore.QSize(640, 480))
        self.imgLabel.setText("")
        self.imgLabel.setObjectName("imgLabel")
        self.verticalLayout.addWidget(self.imgLabel)

        self.retranslateUi(CameraWidget)
        QtCore.QMetaObject.connectSlotsByName(CameraWidget)

    def retranslateUi(self, CameraWidget):
        _translate = QtCore.QCoreApplication.translate
        CameraWidget.setWindowTitle(_translate("CameraWidget", "Form"))
        self.label_2.setText(_translate("CameraWidget", "MOV_X"))
        self.label_3.setText(_translate("CameraWidget", "MOV_Y"))
        self.startButton.setText(_translate("CameraWidget", "start"))
        self.label.setText(_translate("CameraWidget", "X"))
        self.label_4.setText(_translate("CameraWidget", "Y"))
